### GET info
GET http://localhost:3001/info

### GET all persons
GET http://localhost:3001/api/persons

### GET 1 person
GET http://localhost:3001/api/persons/1

### GET non existing person
GET http://localhost:3001/api/persons/343243