### GET info
GET http://localhost:3001/info

### GET all persons
GET http://localhost:3001/api/persons

### GET 1 person
GET http://localhost:3001/api/persons/69a7fb972e347a07ff3929da

### GET non existing person
GET http://localhost:3001/api/persons/343243

### POST a new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "hello",
    "number": "123-382929"
}

### POST a person without a name
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-382929"
}

### POST a person with a name too short
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-382929",
    "name": "ab"
}

### POST a person without a number
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "vscode rest"
}

### POST a person who already exists
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123-382929"
}

### DELETE 1 person
DELETE  http://localhost:3001/api/persons/69a7e5eea86163bba95cd76a

### GET unknown endpoint
GET http://localhost:3001/api/foo